services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development 
      - MONGODB_DB=users
      - MONGODB_HOST=mongo
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=admin
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./application:/app/application